### ISSUE TITLE
Link to 

### ISSUE THREAD

**Issue by geordielad** [tableau/mobile-app-bootstrap#4]
README.md has bad link

> ... difference between Cordova and Phonegap 

has http://phonegap.com/blog/2012/03/19/phonegap-cordova-and-what-e2-80-99s-in-a-name/

results in 404

Should be:

http://phonegap.com/blog/2012/03/19/phonegap-cordova-and-whate28099s-in-a-name/

**Comment by tedwas** [comment]
Thanks for reporting this issue Robin. I have fixed the README.md file.
